#!/usr/bin/env Rscript
# Quick Start Guide for Mobile Scanning

cat("\n╔════════════════════════════════════════════════════════════════╗\n")
cat("║          LIMS Mobile Scanning - Get Started                  ║\n")
cat("╚════════════════════════════════════════════════════════════════╝\n\n")

cat("📋 STEP 1: Generate Labels to Scan\n")
cat("─────────────────────────────────────────────────────────────\n")
cat("• Start the app: Rscript run_app_mobile.R\n")
cat("• Go to browser: http://localhost:3838\n")
cat("• Tab: 'Label Generation'\n")
cat("• Select a site, set range (e.g., 1-50)\n")
cat("• Click 'Generate Labels'\n")
cat("• Print labels or display on screen\n\n")

cat("📱 STEP 2: Connect Your Phone\n")
cat("─────────────────────────────────────────────────────────────\n")
cat("• Find your computer's IP from app startup message\n")
cat("  Example: 192.168.1.100\n")
cat("• On phone browser, enter:\n")
cat("  http://192.168.1.100:3838\n")
cat("• You should see the LIMS app\n\n")

cat("📸 STEP 3: Mobile Scanning Workflow\n")
cat("─────────────────────────────────────────────────────────────\n")
cat("1. Click 'Mobile Scan' tab\n")
cat("2. Keep 'Scanned Plant ID' field focused (or tap it)\n")
cat("3. Use phone camera to scan QR code on label\n")
cat("   • Best way: Use native Camera app → 'Look Up'\n")
cat("   • Alternative: Use dedicated QR scanner app\n")
cat("4. The plant ID auto-fills (e.g., ST0001-P0001)\n")
cat("5. App auto-detects and submits instantly\n")
cat("6. See success message and proceed to next label\n\n")

cat("✅ LABEL FORMAT\n")
cat("─────────────────────────────────────────────────────────────\n")
cat("Left side:        Right side:\n")
cat("ST0001-P0001      [QR CODE]\n")
cat("ST0001            (encodes: ST0001-P0001)\n")
cat("2026-03-25\n\n")

cat("🔧 TROUBLESHOOTING\n")
cat("─────────────────────────────────────────────────────────────\n")
cat("Q: QR code doesn't auto-fill\n")
cat("A: Try these:\n")
cat("   1. Make sure 'Scanned Plant ID' field is focused\n")
cat("   2. Manually paste the scanned ID\n")
cat("   3. Type the ID manually (ST0001-P0001 format)\n\n")

cat("Q: Phone can't connect to app\n")
cat("A: Try these:\n")
cat("   1. Verify phone on same WiFi as computer\n")
cat("   2. Verify you're using correct IP address\n")
cat("   3. Restart app with: Rscript run_app_mobile.R\n")
cat("   4. Check firewall isn't blocking port 3838\n\n")

cat("Q: QR code quality is poor\n")
cat("A: Try these:\n")
cat("   1. Print labels at higher resolution\n")
cat("   2. Display on bright screen\n")
cat("   3. Ensure good lighting when scanning\n")
cat("   4. Hold phone steady 6-12 inches from code\n\n")

cat("📊 DATABASE TRACKING\n")
cat("─────────────────────────────────────────────────────────────\n")
cat("Each scan is recorded:\n")
cat("• Tab: 'Inventory View' → 'Recent Mobile Check-Ins'\n")
cat("• Shows: Plant ID, Location, Timestamp\n")
cat("• Data persists in SQLite database\n\n")

cat("🚀 READY TO START?\n")
cat("─────────────────────────────────────────────────────────────\n")
cat("Run this to start with mobile access:\n")
cat("  Rscript run_app_mobile.R\n\n")
